# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScribaVitae', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(default=' ', max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='literarywork',
            name='content',
            field=models.TextField(default=' ', max_length=1000000),
            preserve_default=False,
        ),
    ]
